name: main-workflow

on:
  release:
    types:
      - created

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  IMAGE_NAME: primes

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: ./app/package-lock.json
          node-version-file: ./app/.nvmrc
      - name: Install dependencies
        id: dependencies_installed
        run: cd app/ && npm ci
      - name: Lint code
        run: cd app/ && npm run lint
      - name: Do Jest tests
        run: cd app/ && npm run test
      - name: Do E2E tests
        run: cd app/ && npm run test:e2e
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
          target: production
